version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:981265949290:task-definition/swiggy-task:4"
        LoadBalancerInfo:
          ContainerName: "swiggy-container"
          ContainerPort: 80