sonar.projectKey=swiggy-clone
sonar.projectName=Swiggy Clone
sonar.projectVersion=1.0
sonar.sources=client/src,server/src
sonar.exclusions=**/node_modules/**,**/build/**,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info